chat/urls.py
from django.urls import path

from . import apps
from . import views

app_name = apps.ChatConfig.name

urlpatterns = [
    path('', views.room_view, name='index'),
]

user/urls.py
from django.urls import path

from . import apps
from . import views

app_name = apps.UserConfig.name

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('signup', views.signup_view, name='signup'),
]

webchat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('chat.urls', namespace='chat')),
]

chat/models.py
from django.db import models


class ChatRoom(models.Model):
    name = models.CharField(max_length=15, unique=True)


class ChatMessage(models.Model):
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
    username = models.CharField(max_length=30)
    content = models.CharField(max_length=256)
    created_at = models.DateTimeField(auto_now=True)

chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.text import slugify

from chat.models import ChatMessage, ChatRoom


@login_required(login_url='/user/login')
def room_view(request):
    room_name = request.GET.get('room_name', 'global')
    room_slug = slugify(room_name)

    if room_name != room_slug:
        return redirect(reverse('chat:index') + f'?room_name={room_slug}')

    room, created = ChatRoom.objects.get_or_create(name=room_name)
    messages = ChatMessage.objects.filter(room=room.pk).order_by('-created_at')[:50]
    return render(request, 'chat/room.html', {
        'room_name': room_name,
        'latest_messages': reversed(messages),
    })

user/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import render, redirect
from django.urls import reverse


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(request.GET.get('next', reverse('chat:index')))
    else:
        form = AuthenticationForm()
    return render(request, 'user/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect(reverse('user:login'))


def signup_view(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('user:login'))
    return render(request, 'user/signup.html', {'form': form})

chat/templates/chat/room.html
{% extends 'core/layout.html' %}
{% block content %}
<div class="row" id="chat-log">
    {% for message in latest_messages %}
        {% if user.username == message.username %}
            <div class="col-8 offset-4">
                <div class="alert alert-success">
                    <b>{{ message.username }}</b>
                    <small class="text-muted">{{ message.created_at }}</small>
                    <p>{{ message.content }}</p>
                </div>
            </div>
        {% else %}
            <div class="col-8">
                <div class="alert alert-primary">
                    <b>{{ message.username }}</b>
                    <small class="text-muted">{{ message.created_at }}</small>
                    <p>{{ message.content }}</p>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
<div id="chat-message-area" class="col-md-12">
    <div class="form-row">
        <div class="col-10">
            <textarea id="chat-message-text" class="form-control" rows="1"></textarea>
        </div>
        <div class="col-2 text-center">
          <button id="chat-message-send" type="submit" class="btn btn-lg btn-primary">Send</button>
        </div>
    </div>
</div>
{% endblock content %}

{% block js_scripts %}
<script>
    var roomName = '{{ room_name }}';
    var username = '{{ user.username }}';

    var chatSocket = new WebSocket(
        'ws://' + window.location.host + '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        if(username == data['username']) {
            $('#chat-log').append(
                '<div class="col-8 offset-4"><div class="alert alert-success"><b>'
                + data['username'] + '</b> <small class="text-muted">' + data['datetime']
                + '</small><p>' + data['message'] + '</p></div></div>'
            );
        } else {
            $('#chat-log').append(
                '<div class="col-8"><div class="alert alert-primary"><b>'
                + data['username'] + '</b> <small class="text-muted">' + data['datetime']
                + '</small><p>' + data['message'] + '</p>'
            );
        }
    };

    chatSocket.onclose = function(e) {
        console.log(e);
        console.error('Chat socket closed unexpectedly');
    };

    $('#chat-message-text').focus();
    $('#chat-message-text').keyup(function(e) {
        if (e.keyCode === 13) {  // enter, return
            $('#chat-message-send').click();
        }
    });

    $('#chat-message-send').click(function(e) {
        var messageInputDom = $('#chat-message-text');
        if(messageInputDom.val() !== '') {
            chatSocket.send(JSON.stringify({
                'message': messageInputDom.val()
            }));
            messageInputDom.val('');
            $('#chat-message-text').focus();
        }
    });
</script>
{% endblock js_scripts %}

templates/core/layout.html
{% load i18n %}
<!DOCTYPE html>
<html lang="{% trans 'en' %}">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% trans 'Web Chat' %}{% endblock title %}</title>
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand">WebChat</a>
        </div>
        {% if user.is_authenticated %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
            <form class="form-inline my-2 my-lg-0" method="get" action="/">
                <input class="form-control mr-sm-2" name='room_name' type="text" placeholder="Enter chat room name">
            </form>
        </div>
        {% endif %}
    </nav>
<div id="main" class="container">
{% block content %}{% endblock content %}
</div>
<script src="//code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% block js_scripts %}{% endblock js_scripts %}
</body>
</html>

user/templates/user/login.html
{% extends 'core/layout.html' %}
{% block title %}Login{% endblock title %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Login</button>
</form>
<p>Don't have an account? <a href="{% url 'user:signup' %}">Sign up!</a></p>
{% endblock content %}

user/templates/user/signup.html
{% extends 'core/layout.html' %}
{% block title %}Sign Up{% endblock title %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    {{ form.errors }}
    <button type="submit" class="btn btn-primary">Sign Up</button>
    <p>Already have an account? <a href="{% url 'user:login' %}">Log in!</a></p>
</form>
{% endblock content %}